MSIGDB_VERSION: "v2022.1.Mm"
# e.g. v7.5.1|v2022.1.Mm/

# Dashed list of msigdb collection of geneset to be investigated
MSIGDB_TYPES:
        "v7.5.1":
                - "h.all"
                - "c1.all"
                - "c2.cgp"
                - "c2.cp.biocarta"
                - "c2.cp.kegg"
                - "c2.cp.reactome"
                - "c2.cp"
                - "c3.mir" 
                - "c3.tft"
                - "c4.cgn"
                - "c4.cm"
                - "c5.go.mf"
                - "c5.go.bp"
                - "c5.go.cc"
                - "c6.all"
                - "c7.all"
                - "c8.all"
        "v2022.1.Mm":
                - "m1.all"
                - "m2.cgp"
                - "m2.cp.biocarta"
                - "m2.cp.reactome"
                - "m2.cp"
                - "m2.cp.wikipathways"
                - "m3.gtrd"
                - "m3.mirdb"
                - "m5.go.bp"
                - "m5.go.cc"
                - "m5.go.mf"
                - "m5.go"
                - "m5.mpt"
                - "m8.all"
                - "mh.all"



RNK_METRIC: "logFC_pval"
# e.g. logFC|logFC_pval

MAX_GENES_IN_SET: 5000
MIN_GENES_IN_SET: 5

GSEA_WEIGHT: 0 
# e.g. 0|1
# https://www.biostars.org/p/263074/

MSIGDB_DIR: DAP_REFERENCE_ROOT + "/msigdb/dataset/" + MSIGDB_VERSION


#################
#
# Publish params
#

GSEA_PUBLISH_HOST: olilab01.ateneo.unito.it
GSEA_PUBLISH_USER: imolineris
